### ISSUE TITLE
could you provide the following files for training?

### ISSUE THREAD

**Issue by LiangHann** [guxinqian/AP3D#1]
self.train_name_path = osp.join(self.root, 'info/train_name.txt')
        self.test_name_path = osp.join(self.root, 'info/test_name.txt')
        self.track_train_info_path = osp.join(self.root, 'info/tracks_train_info.mat')
        self.track_test_info_path = osp.join(self.root, 'info/tracks_test_info.mat')
        self.query_IDX_path = osp.join(self.root, 'info/query_IDX.mat')

could you provide the info folder?

**Comment by guxinqian** [comment]
My apologies for the delayed response. It can be downloaded from this project: https://github.com/liangzheng06/MARS-evaluation
