### ISSUE TITLE
Duke数据集

### ISSUE THREAD

**Issue by 1215481871** [guxinqian/AP3D#11]
请问一下为什么duke数据集的结果 非常低？

**Comment by guxinqian** [comment]
能具体描述一下吗，是到不了论文结果，还是说论文结果低？

**Comment by 1215481871** [comment]
对 跑您的C2D baseline 结果只有七八十

**Comment by 1215481871** [comment]
我只更改了parser里面的 --root 和 --dataset，请问还有什么需要更改吗

**Comment by guxinqian** [comment]
你需要跑一下test.py，train.py的测试只用了4帧，所以点会低很多。

**Comment by 1215481871** [comment]
好的 谢谢
