### ISSUE TITLE
Effect of inflate_* functions

### ISSUE THREAD

**Issue by InnovArul** [guxinqian/AP3D#12]
I require a small clarification on my understanding of inflate_* functions.
If time_dim = 1, the inflate_* functions still behave like 2D functions. 
i.e., inflate_conv will make the conv2d layer to conv3d layer, but still behave like conv2d layer, since time_dim=1.
Is that correct? 

Or Is there any other advantage in inflate_* functions?

Thanks in advance!

**Comment by guxinqian** [comment]
Yes, it is.

**Comment by InnovArul** [comment]
thanks!
