### ISSUE TITLE
关于目录

### ISSUE THREAD

**Issue by 1691077362** [guxinqian/AP3D#15]
python train.py --root /home/guxinqian/data/ -d mars --arch ap3dres50 --gpu 0,1 --save_dir log-mars-ap3d
这个mar文件夹是用来存放什么的。

**Comment by 1691077362** [comment]
mars这个文件夹是这么放的吗/home/guxinqian/data/mars

**Comment by 1691077362** [comment]
![捕获](https://user-images.githubusercontent.com/91247734/181696481-43579a7c-7281-42dd-955e-e30e51aae08f.PNG)
![捕获1](https://user-images.githubusercontent.com/91247734/181696492-5cb955b3-ea3b-470e-92ea-fff71577f144.PNG)
![捕获2](https://user-images.githubusercontent.com/91247734/181696495-1675154e-6de1-4fb3-907c-d260713fc624.PNG)
![捕获3](https://user-images.githubusercontent.com/91247734/181696502-4cd81e62-3af2-497b-9479-662cb00db1c3.PNG)
![捕获4](https://user-images.githubusercontent.com/91247734/181696505-f174629a-4cae-4923-8582-2413eccf8ace.PNG)
![捕获5](https://user-images.githubusercontent.com/91247734/181696509-357c7fc3-a041-48a4-a86a-43a7beedfdb1.PNG)
![捕获6](https://user-images.githubusercontent.com/91247734/181696512-2fb5bca8-01c7-419f-a28c-8a4adfc4807d.PNG)
我建的文件夹是否都正确啊
我在 start train出现这个错误，我改完路径后start train不出现这个错误了。但是在test部分出现这个错误了，所以我想知道我的路径是否还有问题。

==> Start training
C:\Users\administer\.conda\envs\p\lib\site-packages\torch\optim\lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
F:\YDH\spxrcsb\TKP-master\utils\losses.py:108: UserWarning: This overload of addmm_ is deprecated:
        addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
        addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1050.)
  img_distmat.addmm_(1, -2, images, images.t())
Epoch1 Time:593.4s Data:17.5s vXent:6.6427 iXent:6.6635 TKP_F:4.4849 TKP_D:0.4471 i2v:0.2863 v2i:0.4856 i2i:0.5366 v2v:0.2403 vAcc:3.37% iAcc:3.37%
==> Test
Extract video features
Traceback (most recent call last):
  File "train.py", line 471, in <module>
    main()
  File "train.py", line 208, in main
    rank1 = test(vid_model, img_model, queryloader, galleryloader, queryimgloader, galleryimgloader, use_gpu)
  File "train.py", line 341, in test
    for batch_idx, (vids, pids, camids) in enumerate(queryloader):
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\YDH\spxrcsb\TKP-master\utils\video_loader.py", line 116, in __getitem__
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: stack expects a non-empty TensorList

**Comment by guxinqian** [comment]
不好意思回复晚了。应该是/home/guxinqian/data/MARS。路径有两部分，root是数据集的根目录，每个数据集命名在各个dataset的定义里修改。
