### ISSUE TITLE
Details about the Deformable 3D Conv in Table 2

### ISSUE THREAD

**Issue by YingqianWang** [guxinqian/AP3D#4]
Excellent work! I noticed that you have compared different approaches for temporal information modeling in Table 2. I wonder how did you perform Deformable 3D Conv? Is it identical to our recently published D3Dnet? (https://github.com/XinyiYing/D3Dnet)

D3D is an effective approach for motion-aware spatio-temporal modeling and works well for video super-resolution. Did it fail in the Video-based Person ReID task?

**Comment by guxinqian** [comment]
I have attempted to use Deformable Conv to learn the offset on the adjacent frame. But compared with C2D baseline, it got worse results. 
In my version, just the Conv kernels on the adjacent frame are deformable and the Conv kernels on the central frame are original Conv.
