### ISSUE TITLE
Replicate only I3D results 

### ISSUE THREAD

**Issue by abhishekaich27** [guxinqian/AP3D#5]
Hi Xinqian, 

To replicate only I3D results, do we need to change anything else except `AP3D.APP3DC ---> AP3D.I3D` in `L168` of `ResNet.py`? If I only do this change, I get 3% mAP difference according to Table 1.

**Comment by guxinqian** [comment]
Yes, only L168 needs to be changed. 
Batchsize, the num of GPUs and the version of pytorch may impact the results. In general, 1% error is reasonable.
In addition, running test-all.py is necessary, because the process of test in train.py only uses 4 frames per video.
