### ISSUE TITLE
为什么AP3D当中大量的conv2d作为参数传入函数，却没找到来源

### ISSUE THREAD

**Issue by ximu1211** [guxinqian/AP3D#6]
AP3D中def __init__(self, conv2d, **kwargs): 之类的函数中将conv2d作为参数传入，但是没找到它是怎么申明的，是直接用的torch.nn.Conv2d吗

**Comment by guxinqian** [comment]
python中传参不需要声明，你直接去ResNet.py里看是怎么调用的就行。类型的话就是torch.nn.Conv2d。

**Comment by ximu1211** [comment]
> python中传参不需要声明，你直接去ResNet.py里看是怎么调用的就行。类型的话就是torch.nn.Conv2d。

可能是我表述的问题，我没找到这个参数具体是哪里传入，我看了一下ResNet.py中，比如说，
layer3d = Bottleneck3D(layer2d, AP3D.C2D, inflate_time=False)
这里调用了AP3D，但也没有产生参数的传入

**Comment by guxinqian** [comment]
你去看Bottleneck3D的定义，一步一步传参就过去了啊
