### ISSUE TITLE
为什么我train中的pids恒为相等值

### ISSUE THREAD

**Issue by kanagi2587** [guxinqian/AP3D#7]
如题，下载了您的源代码和MARS数据集，进行源代码的运行时

    for batch_idx, (vids, pids, _) in enumerate(trainloader):

中总是满足
if (pids-pids[0]).sum() == 0:
            # can't compute triplet loss
            continue
即pids总是相等的一组值。这是为什么

**Comment by guxinqian** [comment]
是不是trainloader没有shuffle？正常情况下batchsize设为32基本不会出现这种情况。设成16偶尔会这样
