### ISSUE TITLE
请问在这个项目中resnet50中对应卷积的weight是否十分重要

### ISSUE THREAD

**Issue by Lkinyuu** [guxinqian/AP3D#8]
在尝试将该项目迁移到其它框架上，由于特殊的问题无法加载权重，    因此在训练过程中出现欠拟合情况，loss无法下降，准确率也无法提升。  是否不加载这个权重就会难以拟合

**Comment by guxinqian** [comment]
imagenet预训练参数还是挺重要的吧，从头训收敛的慢应该挺正常的。
